name: Windows纯被控精简版
on:
  workflow_dispatch:

jobs:
  build-windows-headless:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 配置 Rust 工具链
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: 自动配置 vcpkg 依赖
        uses: microsoft/setup-vcpkg@v1

      - name: 编译纯被控端
        run: cargo build --release --features headless
        env:
          RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
          RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-被控端-windows-x64
          path: target/release/rustdesk.exe
